/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as R500RouteImport } from './routes/500'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownOpenapiDotjsonRouteImport } from './routes/[.]well-known/openapi[.]json'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale/projects/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as DotwellKnownAgentSkillsSiteDotmdRouteImport } from './routes/[.]well-known/agent-skills/site[.]md'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale/projects/$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenapiDotjsonRoute =
  DotwellKnownOpenapiDotjsonRouteImport.update({
    id: '/.well-known/openapi.json',
    path: '/.well-known/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/$locale/projects/',
  path: '/$locale/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/$locale/blog/',
  path: '/$locale/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsSiteDotmdRoute =
  DotwellKnownAgentSkillsSiteDotmdRouteImport.update({
    id: '/.well-known/agent-skills/site.md',
    path: '/.well-known/agent-skills/site.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/$locale/projects/$slug',
  path: '/$locale/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openapi.json': typeof DotwellKnownOpenapiDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/agent-skills/site.md': typeof DotwellKnownAgentSkillsSiteDotmdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openapi.json': typeof DotwellKnownOpenapiDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale': typeof LocaleIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/agent-skills/site.md': typeof DotwellKnownAgentSkillsSiteDotmdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/archive': typeof ArchiveRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openapi.json': typeof DotwellKnownOpenapiDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/agent-skills/site.md': typeof DotwellKnownAgentSkillsSiteDotmdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/archive'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openapi.json'
    | '/.well-known/openid-configuration'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/tags/$tag'
    | '/$locale/'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/agent-skills/site.md'
    | '/.well-known/mcp/server-card.json'
    | '/$locale/blog/'
    | '/$locale/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/archive'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openapi.json'
    | '/.well-known/openid-configuration'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/tags/$tag'
    | '/$locale'
    | '/blog'
    | '/projects'
    | '/tags'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/agent-skills/site.md'
    | '/.well-known/mcp/server-card.json'
    | '/$locale/blog'
    | '/$locale/projects'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/archive'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openapi.json'
    | '/.well-known/openid-configuration'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/tags/$tag'
    | '/$locale/'
    | '/blog/'
    | '/projects/'
    | '/tags/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/agent-skills/site.md'
    | '/.well-known/mcp/server-card.json'
    | '/$locale/blog/'
    | '/$locale/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  ArchiveRoute: typeof ArchiveRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  DotwellKnownOpenapiDotjsonRoute: typeof DotwellKnownOpenapiDotjsonRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  TagsTagRoute: typeof TagsTagRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownAgentSkillsSiteDotmdRoute: typeof DotwellKnownAgentSkillsSiteDotmdRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openapi.json': {
      id: '/.well-known/openapi.json'
      path: '/.well-known/openapi.json'
      fullPath: '/.well-known/openapi.json'
      preLoaderRoute: typeof DotwellKnownOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/$locale/projects'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/$locale/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/site.md': {
      id: '/.well-known/agent-skills/site.md'
      path: '/.well-known/agent-skills/site.md'
      fullPath: '/.well-known/agent-skills/site.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSiteDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/$locale/projects/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  ArchiveRoute: ArchiveRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  DotwellKnownOpenapiDotjsonRoute: DotwellKnownOpenapiDotjsonRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  TagsTagRoute: TagsTagRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownAgentSkillsSiteDotmdRoute: DotwellKnownAgentSkillsSiteDotmdRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
